drop table BANK_USER if exists;
CREATE TABLE BANK_USER (
	ID bigint identity primary key,
    LOGIN VARCHAR(50),
    USER_PASSWORD VARCHAR(50),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50));
    
drop table PAYEE if exists;  
CREATE TABLE PAYEE (
	ID bigint identity primary key,
    ACCOUNT VARCHAR(50),
    NAME VARCHAR(50),
    ADDRESS VARCHAR(50),
    OWNER_ID bigint,
    FOREIGN KEY (OWNER_ID) 
    REFERENCES BANK_USER(ID));
    
insert into BANK_USER (LOGIN, USER_PASSWORD, FIRST_NAME, LAST_NAME) values ('TP8', 'TP8','RAYMOND', 'STOCKHOLM');
insert into BANK_USER (LOGIN, USER_PASSWORD, FIRST_NAME, LAST_NAME) values ('EGD', 'EGD','BERTRAND', 'AVE');
insert into BANK_USER (LOGIN, USER_PASSWORD, FIRST_NAME, LAST_NAME) values ('PLO', 'PLO','PHILIPPE', 'LOUIS');
insert into BANK_USER (LOGIN, USER_PASSWORD, FIRST_NAME, LAST_NAME) values ('NHU', 'NHU','NICOLAS', 'HUET');

-- BANK_USER ID=1 => TP8
-- BANK_USER ID=2 => EGD
insert into PAYEE (ACCOUNT, NAME, ADDRESS, OWNER_ID) values ('COMPTE_1', 'STOCKHOLM','2 RUE ALAIN FOURNIER', 1);
insert into PAYEE (ACCOUNT, NAME, ADDRESS, OWNER_ID) values ('COMPTE_2', 'STOCKHOLM','2 RUE ALAIN FOURNIER', 1);
insert into PAYEE (ACCOUNT, NAME, ADDRESS, OWNER_ID) values ('COMPTE_1', 'AVE','LUXEMBOURG', 2);    